Refactor update-package-version

diff --git a/.github/actions/update-package-version/action.yml b/.github/actions/update-package-version/action.yml
--- a/.github/actions/update-package-version/action.yml
+++ b/.github/actions/update-package-version/action.yml
@@ -2,12 +2,9 @@ name: "Get updated package version"
 description: "Generate appropriate new package version by current version and updated state."
 
 inputs:
-  curr-package-version:
-    required: true
-    description: "Current package version"
   updated-state:
     required: true
-    description: "Updated state (got from openapi-diff tool)"
+    description: "Updated state (no_changes, incompatible, compatible)"
 
 outputs:
   new-package-version:
@@ -17,19 +14,26 @@ outputs:
 runs:
   using: "composite"
   steps:
-    - name: "Setup Python"
-      uses: actions/setup-python@v3
+    - name: 'Get previous tag'
+      id: previous_tag
+      uses: WyriHaximus/github-action-get-previous-tag@v1
+    - name: 'Get next possible versions'
+      id: semvers
+      uses: "WyriHaximus/github-action-next-semvers@v1"
       with:
-        python-version: '3.x'
-    - name: "Install dependencies"
-      run: pip install -r utils/requirements.txt
-      shell: bash
-    - name: "Run script"
-      id: gen-new-version
+        version: ${{steps.previous_tag.outputs.tag}}
+    - name: "Find appropriate update version"
       run: |
-        new_package_version=$(python utils/update_package_version.py \ 
-          --curr-version "${{inputs.curr-package-version}}" \
-          --updated-state "${{inputs.updated-state}}"
-        )
+        new_package_version=""
+        if [[ "${{inputs.updated-state}}" == 'compatible' ]]; then
+          new_package_version="${{steps.semvers.outputs.minor}}"
+        elif [[ "${{inputs.updated-state}}" == 'incompatible' ]]; then
+          new_package_version="${{steps.semvers.outputs.major}}"
+        elif [[ "${{inputs.updated-state}}" == 'no_changes' ]]; then
+          new_package_version="${{steps.previous_tag.outputs.tag}}"
+        else
+          echo "Invalid updated state. Expected values: 'no_changes', 'incompatible', 'compatible'.";
+          exit 1;
+        fi
         echo "::set-output name=new_package_version::$new_package_version"
       shell: bash
